language: php
php:
  - '7.3'
  - '7.4'
  - '8.0'

branches:
  only:
    - master

install:
  - composer install --dev

script:
  - vendor/bin/phpcs -p --standard=PSR12 src
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit
  - php check-coverage.php coverage.xml 100

after_success:
  - travis_retry mkdir -p build/logs && php vendor/bin/php-coveralls -x coverage.xml -v

env:
  - XDEBUG_MODE=coverage
